Adding "Unrealistic forces in Unity" test scene
Virtana/UnityRobotSimIssues pull request #3
Opened 2020-02-21 18:40 UTC by chris24sahadeo

2020-02-23 12:36 UTC, vpradeep07 requested changes
Some comments inline.  Some meta points:
* Ideally, the unexpected behavior will be obvious, without the user interacting with the scene.  Here are 2 ways you could show this:
  * Idea 1: Add a script that moves the magnet in a sinusoidal linear motion
  * Idea 2: Create two instances of the current setup, side by side.  One will show the magnet working as expected (centered on the block), and the other will show the magnet not working as expected (near the edge of the block)
* Please update the game view camera to have a more useful viewpoint.
* Once this is merged (or about to be merged), please add an animated gif to the PR that shows what's happening in the scene.  This will help for future reference, so that folks don't have to fire up the entire project to see what's going on.

2020-02-23 12:36 UTC, vpradeep07 commented on minimal_test_cases/Assets/force_torque_issue/AddForce.cs
> +        }
Having defaults isn't really adding much towards conveying the problem at hand, and just results in additional code & logic that readers need to parse through.  I'd suggesting stripping this code out, along with the other defaults.
As an alternative, it's also reasonable to have error checking on the input values, and then print errors (or crash the app) if the values are not set as expected.

2020-02-23 12:36 UTC, vpradeep07 commented on minimal_test_cases/Assets/force_torque_issue/AddForce.cs
> +        hitObject.AddForceAtPosition(force, hitPointInWorld);
I was sometimes getting this error:
```
NullReferenceException: Object reference not set to an instance of an object
AddForce.FixedUpdate () (at Assets/force_torque_issue/AddForce.cs:55)
```

2020-03-03 14:33 UTC, chris24sahadeo reviewed
Changes made. Requesting review.

2020-03-03 14:37 UTC, vpradeep07 approved these changes
LGTM.  Thanks!

2020-03-03 14:46 UTC, merged